 
 /*------------------------------------------------------------------------
    File        : baseBE
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Administrator
    Created     : Tue Feb 02 14:40:34 UTC 2016
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS app.baseBE: 

{inc/dsFilter.i PROTECTED}

END CLASS.